### ISSUE TITLE
A mistake and a question

### ISSUE THREAD

**Issue by wangc16** [ai-tor/PyTorchSRGAN#2]
A good project.
But, there is a mistake in the last line of 'train', which made me confused.  (G --> D)
So, how well does it work?

**Comment by ai-tor** [comment]
Hi @wangc16 

I haven't had time to properly sit and fine-tune the hyperparameters. It is being difficult to balance the generator and the discriminator, but this is a common issue with GANs. I don't get super resolution yet, I just recover the original resolution for now.
