### ISSUE TITLE
questions about Densenet blocks

### ISSUE THREAD

**Issue by icoz69** [ai-tor/PyTorchSRGAN#3]
hi, thanks for the code. 
i have a question about the densenet blocks. i noticed each block returns x which is a combination of previous inputs and y,the output of last conv. however, in this way N desenet blocks are actually one big densenet block.  should it return y instead?

**Comment by ai-tor** [comment]
Hi @icoz69,

That is actually right. I didn't take inspiration directly from the original DenseNet paper but from https://arxiv.org/pdf/1611.09326.pdf, which uses a small variant for semantic segmentation. This avoid loosing information from the input, which I thought it may help for the case of Super Resolution too.

**Comment by icoz69** [comment]
thanks for your reply.  why dont you use the discriminator architecture from the original SRGAN paper?

**Comment by ai-tor** [comment]
Fun 😁

**Comment by icoz69** [comment]
sorry？ 😄

**Comment by suke27** [comment]
./train --cuda  is it Super resolution for CIFAR-100 , or classification for CIFAR-100
