### ISSUE TITLE
the initialization of network weights

### ISSUE THREAD

**Issue by weizequan** [ai-tor/PyTorchSRGAN#7]
Hi, i don't find the code about the initialization of network weights from all files, like nn.init.normal(w). So, which strategy for initialization do you use?

**Comment by aitorzip** [comment]
Hi @qigreen,

I use the Pytorch's default, it is uniform between -stdev and stdev where stdev is 1/sqrt(n_weights).

You can check it out here: https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/conv.py
